### ISSUE TITLE
Doesn't handle connection state of "Timed out"

### ISSUE THREAD

**Issue by roaddolphin** [jp-powers/piactl-checker#1]
Didn't seem to handle when the connection state times out with message "Timed out in 5.0001 seconds" for example, so I added a elif stanza:

if [ $CONNECTSTATUS == "Connected" ]; then
        echo 'Already connected'
elif [[ $CONNECTSTATUS =~ "Timed" ]]; then
        echo "Timed out. Exiting."
        exit 1
else
        /usr/local/bin/piactl connect
        echo 'Reconnecting'
fi

**Comment by jp-powers** [comment]
Apologies for the delay on reply, didn't get a chance to get to this earlier.

Good catch, I appreciate it. I'm adding the stanza now.
